version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      commands:
      - echo Logging into CodeArtifact...
      - aws codeartifact login \
          --tool maven \
          --repository devops-cicd\      
          --domain nextwork \
          --domain-owner 729386420364 \
          --region ap-southeast-2
  build:
    commands:
      - echo Build started on `date`
      - mvn compile
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/devops-web-project.war
  discard-paths: no
